site_name: Vantage SDK Python
site_url: https://github.com/VantageDiscovery/vantage-sdk-python
repo_url: https://github.com/VantageDiscovery/vantage-sdk-python
repo_name: VantageDiscovery/vantage-sdk-python
#strict: true
nav:
  - Home: index.md
  - Reference: api.md
theme:
  logo: assets/vantage_logo_small.png
  name: material
  language: en
  palette:
    primary: custom
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - pymdownx.snippets
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - meta
plugins:
  - mkdocstrings:
      handlers:
        python:
          options:
            parameter_headings: false
            extensions:
              - griffe_fieldz
  - include-markdown
  - search:
      lang: en

watch:
  - vantage_sdk

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js
