# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import (
    BaseModel,
    Field,
    StrictBool,
    StrictInt,
    StrictStr,
    validator,
)


class CollectionImmutable(BaseModel):
    """
    CollectionImmutable
    """

    collection_id: Optional[StrictStr] = Field(
        None,
        description="Immutable.  Unique identifier within an account, 3 to 36 characters long with only lower case letters, numeric digits and \"-\"",
    )
    user_provided_embeddings: Optional[StrictBool] = Field(
        False,
        description="Ignore llm_ fields will provide own embeddings for both ingest and search",
    )
    llm_provider: Optional[StrictStr] = None
    llm_model: Optional[StrictStr] = None
    embeddings_dimension: Optional[StrictInt] = Field(
        None,
        description="The dimensionality or vector size of the embeddings.  Applies to both user provided embeddings and vantage managed embeddings.",
    )
    __properties = [
        "collection_id",
        "user_provided_embeddings",
        "llm_provider",
        "llm_model",
        "embeddings_dimension",
    ]

    @validator('llm_provider')
    def llm_provider_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('OpenAI', 'HuggingFace'):
            raise ValueError(
                "must be one of enum values ('OpenAI', 'HuggingFace')"
            )
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CollectionImmutable:
        """Create an instance of CollectionImmutable from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CollectionImmutable:
        """Create an instance of CollectionImmutable from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CollectionImmutable.parse_obj(obj)

        _obj = CollectionImmutable.parse_obj(
            {
                "collection_id": obj.get("collection_id"),
                "user_provided_embeddings": obj.get("user_provided_embeddings")
                if obj.get("user_provided_embeddings") is not None
                else False,
                "llm_provider": obj.get("llm_provider"),
                "llm_model": obj.get("llm_model"),
                "embeddings_dimension": obj.get("embeddings_dimension"),
            }
        )
        return _obj
