# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional, Union

from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr


class EmbeddingSearchQueryFullAllOfCollection(BaseModel):
    """
    EmbeddingSearchQueryFullAllOfCollection
    """

    account_id: Optional[StrictStr] = None
    collection_id: Optional[StrictStr] = None
    accuracy: Optional[Union[StrictFloat, StrictInt]] = None
    __properties = ["account_id", "collection_id", "accuracy"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(
        cls, json_str: str
    ) -> EmbeddingSearchQueryFullAllOfCollection:
        """Create an instance of EmbeddingSearchQueryFullAllOfCollection from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> EmbeddingSearchQueryFullAllOfCollection:
        """Create an instance of EmbeddingSearchQueryFullAllOfCollection from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return EmbeddingSearchQueryFullAllOfCollection.parse_obj(obj)

        _obj = EmbeddingSearchQueryFullAllOfCollection.parse_obj(
            {
                "account_id": obj.get("account_id"),
                "collection_id": obj.get("collection_id"),
                "accuracy": obj.get("accuracy"),
            }
        )
        return _obj
