# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr

class GlobalSearchPropertiesFilter(BaseModel):
    """
    GlobalSearchPropertiesFilter
    """
    boolean_filter: Optional[StrictStr] = None
    __properties = ["boolean_filter"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> GlobalSearchPropertiesFilter:
        """Create an instance of GlobalSearchPropertiesFilter from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> GlobalSearchPropertiesFilter:
        """Create an instance of GlobalSearchPropertiesFilter from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return GlobalSearchPropertiesFilter.parse_obj(obj)

        _obj = GlobalSearchPropertiesFilter.parse_obj({
            "boolean_filter": obj.get("boolean_filter")
        })
        return _obj


