# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Any, Dict, List, Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr, conlist

class MLTheseTheseInner(BaseModel):
    """
    MLTheseTheseInner
    """
    weight: Union[StrictFloat, StrictInt] = Field(...)
    query_text: Optional[StrictStr] = None
    query_document_id: Optional[StrictStr] = None
    embedding: Optional[conlist(Union[StrictFloat, StrictInt])] = None
    these: Optional[conlist(Dict[str, Any])] = None
    __properties = ["weight", "query_text", "query_document_id", "embedding", "these"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> MLTheseTheseInner:
        """Create an instance of MLTheseTheseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> MLTheseTheseInner:
        """Create an instance of MLTheseTheseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return MLTheseTheseInner.parse_obj(obj)

        _obj = MLTheseTheseInner.parse_obj({
            "weight": obj.get("weight"),
            "query_text": obj.get("query_text"),
            "query_document_id": obj.get("query_document_id"),
            "embedding": obj.get("embedding"),
            "these": obj.get("these")
        })
        return _obj


