# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr


class VantageAPIKey(BaseModel):
    """
    VantageAPIKey
    """

    vantage_api_key_id: Optional[StrictStr] = Field(
        None,
        description="The unique id of the API key to access Vantage API endpoints",
    )
    account_id: Optional[StrictStr] = Field(
        None, description="The account this key is contained within"
    )
    vantage_api_key_created_date: Optional[StrictStr] = Field(
        None, description="date this key was created"
    )
    vantage_api_key_value: Optional[StrictStr] = Field(
        None, description="obfuscated key"
    )
    __properties = [
        "vantage_api_key_id",
        "account_id",
        "vantage_api_key_created_date",
        "vantage_api_key_value",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> VantageAPIKey:
        """Create an instance of VantageAPIKey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "vantage_api_key_id",
                "account_id",
                "vantage_api_key_created_date",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> VantageAPIKey:
        """Create an instance of VantageAPIKey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return VantageAPIKey.parse_obj(obj)

        _obj = VantageAPIKey.parse_obj(
            {
                "vantage_api_key_id": obj.get("vantage_api_key_id"),
                "account_id": obj.get("account_id"),
                "vantage_api_key_created_date": obj.get(
                    "vantage_api_key_created_date"
                ),
                "vantage_api_key_value": obj.get("vantage_api_key_value"),
            }
        )
        return _obj
