# coding: utf-8

"""
    Vantage API

    This is a the API to interact with Vantage Discovery, the amazing Semantic Search Platform in the world.  We enable developers to build magical discovery experiences into their products and websites.  Some useful links: - [TODO: Semantic Search Guide: What Is It And Why Does It Matter?](https://www.bloomreach.com/en/blog/2019/semantic-search-explained-in-5-minutes)

    The version of the OpenAPI document: v1.1.2
    Contact: devrel@vantagediscovery.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import io
import re  # noqa: F401
import warnings
from typing import Optional

from pydantic import Field, StrictStr, ValidationError, validate_arguments
from typing_extensions import Annotated

from vantage.core.http.api_client import ApiClient
from vantage.core.http.api_response import ApiResponse
from vantage.core.http.exceptions import (  # noqa: F401
    ApiTypeError,
    ApiValueError,
)


class DocumentsApi:
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    def __init__(self, api_client=None) -> None:
        if api_client is None:
            api_client = ApiClient.get_default()
        self.api_client = api_client

    @validate_arguments
    def upload_documents(
        self,
        account_id: Annotated[
            StrictStr, Field(..., description="The account id")
        ],
        collection_id: Annotated[
            StrictStr,
            Field(
                ...,
                description="The collection to upload these documents into",
            ),
        ],
        customer_batch_identifier: Annotated[
            Optional[StrictStr],
            Field(
                description="If you have an identifier for this group of records in your system."
            ),
        ] = None,
        **kwargs,
    ) -> None:  # noqa: E501
        """Upload Documents  # noqa: E501

        Upload documents to a collection for indexing  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.upload_documents(account_id, collection_id, customer_batch_identifier, async_req=True)
        >>> result = thread.get()

        :param account_id: The account id (required)
        :type account_id: str
        :param collection_id: The collection to upload these documents into (required)
        :type collection_id: str
        :param customer_batch_identifier: If you have an identifier for this group of records in your system.
        :type customer_batch_identifier: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _request_timeout: timeout setting for this request.
               If one number provided, it will be total request
               timeout. It can also be a pair (tuple) of
               (connection, read) timeouts.
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """
        kwargs['_return_http_data_only'] = True
        if '_preload_content' in kwargs:
            message = "Error! Please call the upload_documents_with_http_info method with `_preload_content` instead and obtain raw data from ApiResponse.raw_data"  # noqa: E501
            raise ValueError(message)
        return self.upload_documents_with_http_info(
            account_id, collection_id, customer_batch_identifier, **kwargs
        )  # noqa: E501

    @validate_arguments
    def upload_documents_with_http_info(
        self,
        account_id: Annotated[
            StrictStr, Field(..., description="The account id")
        ],
        collection_id: Annotated[
            StrictStr,
            Field(
                ...,
                description="The collection to upload these documents into",
            ),
        ],
        customer_batch_identifier: Annotated[
            Optional[StrictStr],
            Field(
                description="If you have an identifier for this group of records in your system."
            ),
        ] = None,
        **kwargs,
    ) -> ApiResponse:  # noqa: E501
        """Upload Documents  # noqa: E501

        Upload documents to a collection for indexing  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True

        >>> thread = api.upload_documents_with_http_info(account_id, collection_id, customer_batch_identifier, async_req=True)
        >>> result = thread.get()

        :param account_id: The account id (required)
        :type account_id: str
        :param collection_id: The collection to upload these documents into (required)
        :type collection_id: str
        :param customer_batch_identifier: If you have an identifier for this group of records in your system.
        :type customer_batch_identifier: str
        :param async_req: Whether to execute the request asynchronously.
        :type async_req: bool, optional
        :param _preload_content: if False, the ApiResponse.data will
                                 be set to none and raw_data will store the
                                 HTTP response body without reading/decoding.
                                 Default is True.
        :type _preload_content: bool, optional
        :param _return_http_data_only: response data instead of ApiResponse
                                       object with status code, headers, etc
        :type _return_http_data_only: bool, optional
        :param _request_timeout: timeout setting for this request. If one
                                 number provided, it will be total request
                                 timeout. It can also be a pair (tuple) of
                                 (connection, read) timeouts.
        :param _request_auth: set to override the auth_settings for an a single
                              request; this effectively ignores the authentication
                              in the spec for a single request.
        :type _request_auth: dict, optional
        :type _content_type: string, optional: force content-type for the request
        :return: Returns the result object.
                 If the method is called asynchronously,
                 returns the request thread.
        :rtype: None
        """

        _params = locals()

        _all_params = [
            'account_id',
            'collection_id',
            'customer_batch_identifier',
        ]
        _all_params.extend(
            [
                'async_req',
                '_return_http_data_only',
                '_preload_content',
                '_request_timeout',
                '_request_auth',
                '_content_type',
                '_headers',
            ]
        )

        # validate the arguments
        for _key, _val in _params['kwargs'].items():
            if _key not in _all_params:
                raise ApiTypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method upload_documents" % _key
                )
            _params[_key] = _val
        del _params['kwargs']

        _collection_formats = {}

        # process the path parameters
        _path_params = {}
        if _params['account_id'] is not None:
            _path_params['account_id'] = _params['account_id']

        if _params['collection_id'] is not None:
            _path_params['collection_id'] = _params['collection_id']

        # process the query parameters
        _query_params = []
        if _params.get('customer_batch_identifier') is not None:  # noqa: E501
            _query_params.append(
                (
                    'customer_batch_identifier',
                    _params['customer_batch_identifier'],
                )
            )

        # process the header parameters
        _header_params = dict(_params.get('_headers', {}))
        # process the form parameters
        _form_params = []
        _files = {}
        # process the body parameter
        _body_params = None
        # set the HTTP header `Content-Type`
        _content_types_list = _params.get(
            '_content_type',
            self.api_client.select_header_content_type(['application/text']),
        )
        if _content_types_list:
            _header_params['Content-Type'] = _content_types_list

        # authentication setting
        _auth_settings = ['BearerAuth']  # noqa: E501

        _response_types_map = {}

        return self.api_client.call_api(
            '/account/{account_id}/collection/{collection_id}/documents',
            'POST',
            _path_params,
            _query_params,
            _header_params,
            body=_body_params,
            post_params=_form_params,
            files=_files,
            response_types_map=_response_types_map,
            auth_settings=_auth_settings,
            async_req=_params.get('async_req'),
            _return_http_data_only=_params.get(
                '_return_http_data_only'
            ),  # noqa: E501
            _preload_content=_params.get('_preload_content', True),
            _request_timeout=_params.get('_request_timeout'),
            collection_formats=_collection_formats,
            _request_auth=_params.get('_request_auth'),
        )
